# Generated by Django 5.2.1 on 2025-05-23 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="footballers",
            name="salary",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="footballers",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ]
            ),
        ),
    ]
